### ISSUE TITLE
Error on build using Mac OS

### ISSUE THREAD

**Issue by oltodo** [jesperhh/qmlfmt#14]
Hello,

I try to build your tool but I meet some troubles. After cloning your repo, I launched this two commands:

```
$ cmake .
$ make
```

An error appear on the second one:

<details>
    <summary>Details</summary>
<pre>
[...]
[ 31%] No patch step for 'QtCreator'
[ 36%] Performing update step for 'QtCreator'
[ 40%] Performing configure step for 'QtCreator'
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:39 (find_package):
By not providing "FindQt5Script.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5Script", but CMake did not find one.

Could not find a package configuration file provided by "Qt5Script" with
any of the following names:

    Qt5ScriptConfig.cmake
    qt5script-config.cmake

Add the installation prefix of "Qt5Script" to CMAKE_PREFIX_PATH or set
"Qt5Script_DIR" to a directory containing one of the above files.  If
"Qt5Script" provides a separate development package or SDK, be sure it has
been installed.

-- Configuring incomplete, errors occurred!
See also "/Users/nbazille/www/qmlfmt/QtCreator-prefix/src/QtCreator-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [QtCreator-prefix/src/QtCreator-stamp/QtCreator-configure] Error 1
make[1]: *** [CMakeFiles/QtCreator.dir/all] Error 2
make: *** [all] Error 2
</pre>
</details>  

---

__Environment:__

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75
```

```
$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by oltodo** [comment]
Thanks for answering!

I tried what you've suggested me. The previous error disappeared but I get a new one at the end:

```
[...]
[ 98%] Building CXX object CMakeFiles/qmljs.dir/src/libs/qmljs/qmljstypedescriptionreader.cpp.o
[ 99%] Building CXX object CMakeFiles/qmljs.dir/src/libs/qmljs/qmljsutils.cpp.o
[ 99%] Building CXX object CMakeFiles/qmljs.dir/src/libs/qmljs/qmljsvalueowner.cpp.o
[ 99%] Building CXX object CMakeFiles/qmljs.dir/src/libs/qmljs/qmljsviewercontext.cpp.o
[100%] Building CXX object CMakeFiles/qmljs.dir/qmljs_autogen/mocs_compilation.cpp.o
[100%] Linking CXX static library Release/libqmljs.a
[100%] Built target qmljs
[ 50%] No install step for 'QtCreator'
[ 54%] Completed 'QtCreator'
[ 54%] Built target QtCreator
Scanning dependencies of target qmlfmt_autogen
[ 59%] Automatic MOC for target qmlfmt
[ 59%] Built target qmlfmt_autogen
Scanning dependencies of target qmlfmt
[ 63%] Building CXX object CMakeFiles/qmlfmt.dir/main.cpp.o
[ 68%] Building CXX object CMakeFiles/qmlfmt.dir/qmlfmt.cpp.o
[ 72%] Building CXX object CMakeFiles/qmlfmt.dir/qmlfmt_autogen/mocs_compilation.cpp.o
[ 77%] Linking CXX executable qmlfmt
Undefined symbols for architecture x86_64:
  "Utils::Internal::filePathUrl(QUrl const&)", referenced from:
      Utils::isFileDrop(QMimeData const*, QList<Utils::DropSupport::FileSpec>*) in libutils.a(dropsupport.cpp.o)
  "Utils::Internal::normalizePathName(QString const&)", referenced from:
      Utils::FileUtils::normalizePathName(QString const&) in libutils.a(fileutils.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [qmlfmt] Error 1
make[1]: *** [CMakeFiles/qmlfmt.dir/all] Error 2
make: *** [all] Error 2
```

Sorry I'm not an export about building C++ apps.

**Comment by jesperhh** [comment]
Hmm, could be a newer/older version of Qt that I have not tested with, what version are you using?
Can you try qmake -v in a terminal?

**Comment by oltodo** [comment]
```
$ qmake -v
QMake version 3.0
Using Qt version 5.5.1 in /Applications/Qt/5.5/clang_64/lib
```

It uses the Qt 5.5.1 version. I can try with a 5.12 version.

**Comment by oltodo** [comment]
Sorry, I used the wrong terminal, I was already using the 5.12 version:

```
$ qmake -v
QMake version 3.1
Using Qt version 5.12.0 in /Applications/Qt/5.12.0/clang_64/lib
```

**Comment by jesperhh** [comment]
I can see that the build automation only builds with 5.10 at the moment, I will take a look at getting it working with Qt 5.12 this week- my guess is that is the reason it does not build.

**Comment by oltodo** [comment]
Ok, I'm going to install the 5.10 version. I've just tested with the 5.5.1, but it doesn't work too.

**Comment by oltodo** [comment]
Argh, not better with the 5.10.1 version, same error. 😞

**Comment by oltodo** [comment]
The problem should come from this line:

https://github.com/jesperhh/qmlfmt/blob/master/qmlfmt.cpp#L108

**Comment by jesperhh** [comment]
My guess is that this is just the first place that triggers the dependency for the reformatting library - if you remove that line it will just fail the next place that uses the reformatter.

I am working on setting up continuous integration for a clang build, I hope that will uncover what the issue is.

**Comment by jesperhh** [comment]
I have created a new branch built on qt creator 4.8.1, can you try that one out? 
https://github.com/jesperhh/qmlfmt/tree/submodulesetc

I have also set up a clang build on it, and it passes, so at least that is not the source of the issue.

**Comment by oltodo** [comment]
I got an error on the `cmake` command:

```
CMake Error at qmljs/CMakeLists.txt:66 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
```

Do you know what it means?

**Comment by jesperhh** [comment]
You need to call git submodule update --init

**Comment by oltodo** [comment]
Ok, thanks, I never use this.

**Comment by oltodo** [comment]
Sorry, but still some errors:

```
[ 98%] Linking CXX executable qmlfmt
Undefined symbols for architecture x86_64:
  "Utils::Internal::filePathUrl(QUrl const&)", referenced from:
      Utils::isFileDrop(QMimeData const*, QList<Utils::DropSupport::FileSpec>*) in libutils.a(dropsupport.cpp.o)
  "Utils::Internal::normalizePathName(QString const&)", referenced from:
      Utils::FileUtils::normalizePathName(QString const&) in libutils.a(fileutils.cpp.o)
  "Utils::Internal::forceMacOSLightAquaApperance()", referenced from:
      Utils::setCreatorTheme(Utils::Theme*) in libutils.a(theme.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by oltodo** [comment]
If it can help:

```
$ clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jesperhh** [comment]
I think I found some of the issue at least - missing include of .mm files. Can you try again in the submodule branch?

**Comment by jesperhh** [comment]
..you need to rerun CMake configure as I have added some new files

**Comment by oltodo** [comment]
I still get this kind of errors but this time more 😞

```
[ 98%] Linking CXX executable qmlfmt
Undefined symbols for architecture x86_64:
  "_NSApp", referenced from:
      Utils::Internal::forceMacOSLightAquaApperance() in libutils.a(theme_mac.mm.o)
  "_NSAppearanceNameAqua", referenced from:
      Utils::Internal::forceMacOSLightAquaApperance() in libutils.a(theme_mac.mm.o)
  "_NSURLNameKey", referenced from:
      Utils::Internal::normalizePathName(QString const&) in libutils.a(fileutils_mac.mm.o)
  "_OBJC_CLASS_$_NSAppearance", referenced from:
      objc-class-ref in libutils.a(theme_mac.mm.o)
  "_OBJC_CLASS_$_NSURL", referenced from:
      objc-class-ref in libutils.a(fileutils_mac.mm.o)
  "_objc_autoreleasePoolPop", referenced from:
      Utils::Internal::filePathUrl(QUrl const&) in libutils.a(fileutils_mac.mm.o)
      Utils::Internal::normalizePathName(QString const&) in libutils.a(fileutils_mac.mm.o)
  "_objc_autoreleasePoolPush", referenced from:
      Utils::Internal::filePathUrl(QUrl const&) in libutils.a(fileutils_mac.mm.o)
      Utils::Internal::normalizePathName(QString const&) in libutils.a(fileutils_mac.mm.o)
  "_objc_msgSend", referenced from:
      Utils::Internal::filePathUrl(QUrl const&) in libutils.a(fileutils_mac.mm.o)
      Utils::Internal::normalizePathName(QString const&) in libutils.a(fileutils_mac.mm.o)
      Utils::Internal::forceMacOSLightAquaApperance() in libutils.a(theme_mac.mm.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by jesperhh** [comment]
And you have the version where I added:
if (APPLE)
	find_library(AppKit AppKit)
	find_library(Foundation Foundation)
	
	target_link_libraries(utils ${AppKit} ${Foundation})
endif()
In qmljs/QMakeLists.txt?

**Comment by oltodo** [comment]
Yes I tried with this version (10be37d5de261a8afd0b60b5c6c7ad2f7c667990)

**Comment by oltodo** [comment]
Sorry I tried with the previous commit. I got this error on `cmake`:

```
CMake Error at qmljs/CMakeLists.txt:89 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "utils".  All uses of target_link_libraries with a target must
  be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * qmljs/CMakeLists.txt:79 (target_link_libraries)
```

**Comment by oltodo** [comment]
Good news, I make some changes and it finally worked!

```diff
-target_link_libraries(utils PRIVATE Qt5::Widgets Qt5::Network Qt5::Concurrent Qt5::Qml)
+# target_link_libraries(utils PRIVATE Qt5::Widgets Qt5::Network Qt5::Concurrent Qt5::Qml)

if(WIN32)
	target_link_libraries(utils PRIVATE user32 iphlpapi ws2_32 shell32)
endif()

if (APPLE)
	find_library(AppKit AppKit)
	find_library(Foundation Foundation)
	
-	target_link_libraries(utils ${AppKit} ${Foundation})
+	# target_link_libraries(utils ${AppKit} ${Foundation})
+	target_link_libraries(utils PRIVATE Qt5::Widgets Qt5::Network Qt5::Concurrent Qt5::Qml ${AppKit} ${Foundation})
endif()
```

**Comment by jesperhh** [comment]
Great! I think it would be enough to just add "PRIVATE" to the line:
```
target_link_libraries(utils ${AppKit} ${Foundation})
```
So I will integrate that in this changeset

**Comment by oltodo** [comment]
Thanks @jesperhh for investigating and fixing!
