### ISSUE TITLE
Update QtCreator to 4.0

### ISSUE THREAD

**Issue by Warezovvv** [jesperhh/qmlfmt#3]
If qmlfmt will use http://download.qt.io/official_releases/qtcreator/4.0/4.0.3/qt-creator-opensource-src-4.0.3.tar.gz this version, problems with "pragma Singleton" and removed "readonly" will dissapear.
Right now I changed URL to 4.0.3 and tryied compile, I have following problems.
```bash
[ 15%] Building CXX object CMakeFiles/utils.dir/src/libs/utils/bracematcher.cpp.o
[ 15%] Building CXX object CMakeFiles/utils.dir/src/libs/utils/filesystemwatcher.cpp.o
[ 16%] Building CXX object CMakeFiles/utils.dir/src/libs/utils/unixutils.cpp.o
/home/crupizkas/Documents/Work/AllView/qmlfmt/.build/QtCreator-prefix/src/QtCreator/src/libs/utils/consoleprocess_unix.cpp: In member function ‘bool Utils::ConsoleProcess::start(const QString&, const QString&)’:
/home/crupizkas/Documents/Work/AllView/qmlfmt/.build/QtCreator-prefix/src/QtCreator/src/libs/utils/consoleprocess_unix.cpp:150:28: error: expected primary-expression before ‘(’ token
             + QLatin1String("/" QTC_REL_TOOLS_PATH "/qtcreator_process_stub");
                            ^
/home/crupizkas/Documents/Work/AllView/qmlfmt/.build/QtCreator-prefix/src/QtCreator/src/libs/utils/consoleprocess_unix.cpp:150:33: error: expected ‘)’ before ‘QTC_REL_TOOLS_PATH’
             + QLatin1String("/" QTC_REL_TOOLS_PATH "/qtcreator_process_stub");
                                 ^
make[5]: *** [CMakeFiles/utils.dir/src/libs/utils/consoleprocess_unix.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/utils.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [QtCreator-prefix/src/QtCreator-stamp/QtCreator-build] Error 2
make[1]: *** [CMakeFiles/QtCreator.dir/all] Error 2
make: *** [all] Error 2
FAIL: 2

```

**Comment by jesperhh** [comment]
Try to get the latest changes, it works now here, at least with Qt 5.7 :-)

**Comment by Warezovvv** [comment]
Nice! Will wait for Qt Creator 4.0 integration :) Really good job with this formatter :)

**Comment by jesperhh** [comment]
Sorry, what I meant was it now works with Qt Creator 4.0 but I have only tested using Qt 5.7, so you should try it now!

**Comment by Warezovvv** [comment]
Ah okay, will try at monday ! :)

**Comment by Warezovvv** [comment]
Tried today. Everything works like a charm. Awesome tool. Thanks!!!

**Comment by jesperhh** [comment]
Great, I will close the issue then :-)
